- name: Creating database for Neutron service
  mysql_db: name=neutron state=present login_user={{ mysql_username }} login_password={{ mysql_root_password }} 
 
- name: Setting up the permissions for the Neutron databases
  mysql_user:
    name: "neutron"
    password: "{{ neutron_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    host: "{{ item }}"
    login_user: "{{ mysql_username }}"
    login_password: "{{ mysql_root_password }}"
  with_items:
    - "%" 
    - "localhost"

- name: Creating neutron user for managing the Nova Service
  os_user: name=neutron domain=default password=redhat123@
  environment:
      - OS_USERNAME: "admin"
      - OS_PASSWORD: "{{ admin_password }}"
      - OS_PROJECT_NAME: "admin"
      - OS_USER_DOMAIN_NAME: "Default"
      - OS_PROJECT_DOMAIN_NAME: "Default"
      - OS_AUTH_URL: "http://{{ keystone_host }}:35357/v3"
      - OS_IDENTITY_API_VERSION: "3"

- name: Assigning admin access to the Neutron user 
  os_user_role: user=neutron role=admin project=service
  environment:
      - OS_USERNAME: "admin"
      - OS_PASSWORD: "{{ admin_password }}"
      - OS_PROJECT_NAME: "admin"
      - OS_USER_DOMAIN_NAME: "Default"
      - OS_PROJECT_DOMAIN_NAME: "Default"
      - OS_AUTH_URL: "http://{{ keystone_host }}:35357/v3"
      - OS_IDENTITY_API_VERSION: "3"

- name: Creating the Neutron service for the Openstack Cloud
  os_keystone_service:
     state: present
     name: neutron
     service_type: network
     description: OpenStack networking Service
  environment:
      - OS_USERNAME: "admin"
      - OS_PASSWORD: "{{ admin_password }}"
      - OS_PROJECT_NAME: "admin"
      - OS_USER_DOMAIN_NAME: "Default"
      - OS_PROJECT_DOMAIN_NAME: "Default"
      - OS_AUTH_URL: "http://{{ keystone_host }}:35357/v3"
      - OS_IDENTITY_API_VERSION: "3"

- name: Creating the endpoints for the Neutron Service
  shell: openstack endpoint create --region RegionOne network {{ item }} http://{{ neutron_host }}:9696 && touch /root/.neutron-{{ item }}-endpoint
  args:
     creates: /root/.neutron-{{ item }}-endpoint
  with_items:
      - public
      - internal
      - admin
  environment:
      - OS_USERNAME: "admin"
      - OS_PASSWORD: "{{ admin_password }}"
      - OS_PROJECT_NAME: "admin"
      - OS_USER_DOMAIN_NAME: "Default"
      - OS_PROJECT_DOMAIN_NAME: "Default"
      - OS_AUTH_URL: "http://{{ keystone_host }}:35357/v3"
      - OS_IDENTITY_API_VERSION: "3"



- name: Installing the required packages for the Neutron service
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
    - openstack-neutron 
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge 
    - ebtables

- name: configuring the Neutron Service
  template: src=network-{{ item.source }} dest={{ item.destination }}
  with_items:
      - { source: "neutron.conf",destination: "/etc/neutron/neutron.conf" }
      - { source: "ml2_conf.ini",destination: "/etc/neutron/plugins/ml2/ml2_conf.ini" }
      - { source: "linuxbridge_agent.ini",destination: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini" }
      - { source: "l3_agent.ini",destination: "/etc/neutron/l3_agent.ini" }
      - { source: "dhcp_agent.ini",destination: "/etc/neutron/dhcp_agent.ini" }

- name: Creating a soft link for the ml2 plugin
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini path=/etc/neutron/plugin.ini state=link

- name: Doing a database sync for Neutron Service
  command: '/bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron'

- name: setting up the permissions for the Neutron logs
  file: path=/var/log/neutron/ owner=neutron group=neutron recurse=yes

- name: Starting the services required for the Neutron
  service: name={{ item }} state=started enabled=yes
  with_items:
      - neutron-server
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - neutron-l3-agent
