- name: Installing the memcached Service
  yum: name={{ item }} state=installed
  with_items:
    - memcached
    - python-memcached

- name: Starting the Memcached Services
  service: name=memcached state=started enabled=yes
